version: '3.8'

services:
  frontend:
    image: luka117wm/portfolio-frontend:latest
    container_name: portfolio-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

  backend:
    image: luka117wm/portfolio-backend:latest
    container_name: portfolio-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=database
      - DB_USER=portfolio_user
      - DB_PASSWORD=portfolio_password
      - DB_NAME=portfolio_db
    depends_on:
      - database
    networks:
      - portfolio-network
    restart: unless-stopped

  database:
    image: mysql:8.0
    container_name: portfolio-database
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=portfolio_db
      - MYSQL_USER=portfolio_user
      - MYSQL_PASSWORD=portfolio_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - portfolio-network
    restart: unless-stopped
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer:latest
    container_name: portfolio-adminer
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - portfolio-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  portfolio-network:
    driver: bridge
